import assert from 'node:assert/strict';
import { useFlowStore,selectActiveDocumentTarget } from '../src/store/flowStore';
import { isPoseReferenceNode } from '../src/types/poseReference';
import { createDocumentSnapshot,documentSnapshotToPersistedWorkflow } from '../src/lib/documentSnapshot';
import { addPoseReferenceToCanvas,generatePoseReference,restorePoseReferences,poseReferenceKey,usePoseReferenceRuntime } from '../src/store/poseReferenceRuntime';

const nodes:any[]=[{id:'any-id',type:'image-input',position:{x:0,y:0},data:{kind:'image-input',label:'自定义名称',status:'idle',imageRole:'reference',imageUrl:'/api/files/source.png'}},{id:'target',type:'virtual-try-on',position:{x:400,y:0},data:{kind:'virtual-try-on',workflowStage:'scene-stabilize',label:'定版',status:'idle'}}];
const edges=[{id:'edge',source:'any-id',target:'target',targetHandle:'pose'}];
assert.equal(isPoseReferenceNode('any-id',nodes,edges),true);
assert.equal(isPoseReferenceNode('any-id',nodes,[{...edges[0],targetHandle:'outfit'}]),false);
useFlowStore.getState().loadFlow({projectName:'Pose test',nodes,edges});
const target=selectActiveDocumentTarget(useFlowStore.getState());
const source='/api/files/source.png';
const key=poseReferenceKey(target,'any-id',source);
const originalFetch=globalThis.fetch;
const originalSave=useFlowStore.getState().saveProjectInTab;
let calls=0;
let resolve: ((value:Response)=>void)|undefined;
useFlowStore.setState({saveProjectInTab:async()=>true});
const result={id:'record',source,kind:'depth',status:'succeeded',result:{image:'data:image/png;base64,AAAA',model:'test'}};
try {
  globalThis.fetch=async()=>{calls++;return new Promise<Response>(r=>{resolve=r;});};
  const pending=generatePoseReference(target,'any-id',source,'depth');
  while(!resolve) await new Promise(r=>setTimeout(r,0));
  await generatePoseReference(target,'any-id',source,'depth');
  assert.equal(calls,1,'duplicate click must not make a second POST');
  useFlowStore.getState().updateNodeDataInTab(target,'any-id',{imageUrl:'/api/files/new.png'});
  resolve(new Response(JSON.stringify(result)));
  await pending;
  assert.equal(usePoseReferenceRuntime.getState().entries[key]?.records.depth,undefined,'late result cannot be attached after source changes');
  useFlowStore.getState().updateNodeDataInTab(target,'any-id',{imageUrl:source});
  resolve=undefined;
  const restoring=restorePoseReferences(target,'any-id',source);
  while(!resolve) await new Promise(r=>setTimeout(r,0));
  useFlowStore.getState().loadFlow({projectName:'Replacement document',nodes,edges});
  (resolve as (value:Response)=>void)(new Response(JSON.stringify({records:[result]})));
  await restoring;
  assert.equal(usePoseReferenceRuntime.getState().entries[key]?.records.depth,undefined,'old epoch cannot receive restored results');
  assert.notEqual(poseReferenceKey(selectActiveDocumentTarget(useFlowStore.getState()),'any-id',source),key);
  const detachedNodes=nodes.map(n=>n.id==='any-id'?{...n,data:{...n.data,poseReference:true,autoConnectTargets:[{targetNodeId:'target',targetHandle:'pose'}]}}:n);
  useFlowStore.getState().loadFlow({projectName:'Manual references',nodes:detachedNodes,edges:[]});
  const detached=selectActiveDocumentTarget(useFlowStore.getState());
  assert.equal(isPoseReferenceNode('any-id',detachedNodes,[]),true);
  useFlowStore.getState().assignImageInputInTab(detached,'any-id',source);
  assert.equal(useFlowStore.getState().tabs.find(t=>t.id===detached.tabId)!.edges.length,0,'legacy upload must not auto-connect pose');
  await addPoseReferenceToCanvas(detached,'any-id',source,'original');
  const tab=()=>useFlowStore.getState().tabs.find(t=>t.id===detached.tabId)!;
  assert.equal(tab().nodes.length,3);
  assert.equal(tab().nodes.at(-1)?.data.label,'姿势原图');
  assert.equal(tab().edges.length,0,'adding a reference must not create edges');
  useFlowStore.getState().undo();
  assert.equal(tab().nodes.length,2,'one undo removes the exported image node');
  useFlowStore.getState().redo();
  assert.equal(tab().nodes.length,3);
  const exportedId=tab().nodes.at(-1)!.id;
  useFlowStore.getState().onConnect({source:exportedId,sourceHandle:'image',target:'target',targetHandle:'pose'});
  assert.equal(useFlowStore.getState().pendingConnectionDraft?.proposedTargetHandle,'pose');
  assert.equal(useFlowStore.getState().confirmPendingConnection('pose'),true);
  assert.equal(tab().edges.length,1,'the user can manually connect the exported image');
  assert.equal(tab().edges[0].source,exportedId);
  const saved=documentSnapshotToPersistedWorkflow(createDocumentSnapshot({...tab(),nodes:tab().nodes.filter(n=>n.data.kind==='image-input'),edges:[]}));
  assert.equal((saved.nodes[0].data as any).poseReference,true,'pose entry survives save/reload without requiring an edge');
  assert.equal((saved.nodes.at(-1)!.data as any).imageUrl,source);
  const detachedKey=poseReferenceKey(detached,'any-id',source);
  usePoseReferenceRuntime.setState(s=>({entries:{...s.entries,[detachedKey]:{records:{depth:result as any},busy:{},errors:{}}}}));
  resolve=undefined;
  const exporting=addPoseReferenceToCanvas(detached,'any-id',source,'depth');
  while(!resolve) await new Promise(r=>setTimeout(r,0));
  const beforeDuplicate=calls;
  await addPoseReferenceToCanvas(detached,'any-id',source,'depth');
  assert.equal(calls,beforeDuplicate);
  useFlowStore.getState().loadFlow({projectName:'Replaced while uploading',nodes,edges});
  (resolve as (value:Response)=>void)(new Response(JSON.stringify({url:'/api/files/depth.png'})));
  await exporting;
  assert.equal(useFlowStore.getState().tabs.find(t=>t.id===detached.tabId)!.nodes.length,2,'old epoch cannot receive exported nodes');
  console.log('Pose runtime: semantic port detection, duplicate click, source and document-epoch boundaries passed');
} finally {
  globalThis.fetch=originalFetch;
  useFlowStore.setState({saveProjectInTab:originalSave});
}
