import sharp from "sharp";
import { test, expect } from "./fixtures";

test("drawing background stays proportional, annotations flatten at full resolution and reopen", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "创作工具", exact: true }).click();
  await page.getByRole("menuitem", { name: /绘画工具/ }).click();
  const dialog = page.getByRole("dialog", { name: "绘画板" });
  const image = await sharp({ create: { width: 400, height: 800, channels: 3, background: "#ff0000" } }).png().toBuffer();
  await dialog.getByLabel("上传底图文件").setInputFiles({ name: "base.png", mimeType: "image/png", buffer: image });
  await expect(dialog.getByRole("status")).toContainText("底图已就绪");
  const board = dialog.locator(".konvajs-content");
  const box = (await board.boundingBox())!;
  expect(box.x).toBeGreaterThanOrEqual(0);
  expect(box.x + box.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  const draw = async (tool: string, y: number) => {
    await dialog.getByRole("button", { name: tool, exact: true }).click();
    await page.mouse.move(box.x + box.width * .4, box.y + box.height * y);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * .6, box.y + box.height * y + 20, { steps: 10 });
    await page.mouse.up();
  };
  await draw("画笔", .4);
  await dialog.getByLabel("线宽", { exact: true }).fill("20");
  await draw("橡皮", .4);
  await dialog.getByLabel("线宽", { exact: true }).fill("6");
  await draw("矩形", .5);
  await draw("椭圆", .6);
  await draw("直线", .7);
  await draw("箭头", .8);
  await dialog.getByRole("button", { name: "文字", exact: true }).click();
  await dialog.getByLabel("文字内容").fill("服装标注");
  await dialog.getByRole("button", { name: "添加文字", exact: true }).click();
  // Replacing a background must not discard annotation objects; undo restores the first image.
  const blue = await sharp({ create: { width: 800, height: 400, channels: 3, background: "#0000ff" } }).png().toBuffer();
  await dialog.getByLabel("上传底图文件").setInputFiles({ name: "replacement.png", mimeType: "image/png", buffer: blue });
  await expect(dialog.getByRole("status")).toContainText("底图已就绪");
  await dialog.getByRole("button", { name: "撤销", exact: true }).click();
  await expect(dialog.getByRole("status")).toContainText("底图已就绪");
  await dialog.getByRole("button", { name: "选择", exact: true }).click();
  await page.mouse.click(box.x + box.width * .06, box.y + box.height * .05);
  const request = page.waitForRequest((r) => r.url().endsWith("/api/drawing-boards/create") && r.method() === "POST");
  await dialog.getByRole("button", { name: "保存画板", exact: true }).click();
  const body = (await request).postDataJSON();
  await expect(dialog).toHaveCount(0);
  expect(body.document.baseImage.width).toBe(400);
  expect(body.document.layers[0].objects.map((o: {kind: string}) => o.kind)).toEqual(["stroke", "stroke", "rectangle", "ellipse", "line", "arrow", "text"]);
  const response = await page.request.get(body.previewImageRef);
  const result = sharp(await response.body());
  const meta = await result.metadata();
  expect(meta.width).toBe(body.document.canvas.width);
  expect(meta.height).toBe(body.document.canvas.height);
  const pixel = async (x: number, y: number) => Array.from(await result.clone().extract({ left: x, top: y, width: 1, height: 1 }).removeAlpha().raw().toBuffer());
  expect(await pixel(512, 200)).toEqual([255, 0, 0]);
  expect(await pixel(100, 200)).toEqual([255, 255, 255]);
  expect(await pixel(512, 430)).toEqual([255, 0, 0]);
  const rgb = await result.clone().removeAlpha().raw().toBuffer();
  let blueHighlightPixels = 0;
  for (let i = 0; i < rgb.length; i += 3) if (rgb[i + 2] > rgb[i] + 30) blueHighlightPixels++;
  expect(blueHighlightPixels).toBe(0);
  const node = page.locator(`.react-flow__node[data-id="${body.nodeId}"]`);
  await node.getByRole("button", { name: /编辑/ }).click();
  await expect(page.getByRole("dialog").getByRole("status")).toContainText("底图已就绪");
  await page.screenshot({ path: `/tmp/neihe-drawing-background-${page.viewportSize()!.width}.png` });
});

test("invalid background upload remains retryable and does not create a board", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "创作工具", exact: true }).click();
  await page.getByRole("menuitem", { name: /绘画工具/ }).click();
  const dialog = page.getByRole("dialog", { name: "绘画板" });
  await expect(dialog.getByRole("button", { name: "上传图片", exact: true })).toBeVisible();
  const count = await page.locator(".react-flow__node").count();
  await dialog.getByLabel("上传底图文件").setInputFiles({ name: "invalid.png", mimeType: "image/png", buffer: Buffer.from("not an image") });
  await expect(dialog.getByRole("alert")).toBeVisible();
  await expect(dialog.getByRole("button", { name: "上传图片", exact: true })).toBeEnabled();
  await expect(page.locator(".react-flow__node")).toHaveCount(count);
  const image = await sharp({ create: { width: 300, height: 400, channels: 3, background: "#aaaaaa" } }).png().toBuffer();
  await dialog.getByLabel("上传底图文件").setInputFiles({ name: "valid.png", mimeType: "image/png", buffer: image });
  await expect(dialog.getByRole("status")).toContainText("底图已就绪");
  await dialog.getByRole("button", { name: "取消", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator(".react-flow__node")).toHaveCount(count);
});
